### ISSUE TITLE
Select a custom Opam repo

### ISSUE THREAD

**Issue by MisterDA** [ocamllabs/duniverse#77]
Hi!

I’m experimenting with Duniverse. How do I chose a custom Opam repository?
I saw the code:
https://github.com/ocamllabs/duniverse/blob/44b74dc6bb97c2a316e749055bd7b8ba338232ca/cli/init.ml#L94-L97
and
https://github.com/ocamllabs/duniverse/blob/44b74dc6bb97c2a316e749055bd7b8ba338232ca/lib/config.ml#L31

Can the repository be selected from the command-line, or do I have to change the value or `duniverse_opam_repo`? What’s the `#duniverse` fragment for in the URI?

Thanks!

**Comment by NathanReb** [comment]
You should indeed be able to select your own opam-repository from the command line by passing it to `duniverse init` with the `--opam-repo <path_or_url>` CLI option.

When pointing to a git repository you can select a particular branch with the `#<branch_name>` suffix, that's what the `#duniverse` part of the default URL is.

Also note that the documentation for this option isn't up to date and that the provided opam-repository isn't used as a complement to the regular one but as a full replacement. That means it should provide all the packages you need and not only dune port of the packages that haven't been ported yet on https://github.com/ocaml/opam-repository.

**Comment by MisterDA** [comment]
Thanks!
I don’t remember how I managed to get duniverse running in the first place, because now I have the same compilation failure as [the CI](https://ci.ocamllabs.io/github/ocamllabs/duniverse/commit/44b74dc6bb97c2a316e749055bd7b8ba338232ca/variant/ubuntu).

**Comment by NathanReb** [comment]
Hmm I'm not getting this error locally but I don't bootstrap dune, I just use the version I installed through opam.

Can you tell me a bit more how you ended up with this error so I can try to reproduce it?

**Comment by MisterDA** [comment]
I did not bootstrap dune or duniverse, I installed dune through Opam, and did a fresh clone of the duniverse repo, and got the same error as the CI.

```
$ opam --version
2.0.6
$ ocaml --version
The OCaml toplevel, version 4.09.0
$ dune --version
2.3.1
$ git clone git@github.com:ocamllabs/duniverse.git
$ cd duniverse
$ make
dune build
    discover duniverse/base.v0.13.0/src/mpopcnt.sexp (exit 2)
(cd _build/default/duniverse/base.v0.13.0/src && discover/discover.exe -o mpopcnt.sexp)
Fatal error: exception Configurator__V1.Fatal_error("Configurator scripts must be run with Dune. To manually run a script, use $ dune exec.")
make: *** [Makefile:6 : build] Error 1
```

**Comment by NathanReb** [comment]
Hmm ok interesting, there might be an issue with duniverse's duniverse.

Can you try running:
```
opam install --deps-only -t .
```
to get the dependencies through opam and see if it works?

I have a local opam switch with all the dependencies installed, I'm running the same versions of dune and OCaml as you are and I get it to build and run the test without issues.

I'll try creating a fresh switch a bit later to see if I can reproduce but in the meantime that might be enough. If it's not try adding `(data_only_dirs duniverse)` to the root dune file. It's not great but at least you should be able to build it!

**Comment by MisterDA** [comment]
Installing the dependencies via Opam did not change anything, apparently duniverse still fetches its dependencies in the `duniverse/` directory and not in Opam tree.
```
opam install ./duniverse.opam 
duniverse is now pinned to git+file:///home/antonin/duniverse#master (version ~dev)
The following actions will be performed:
  ∗ install duniverse ~dev*

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[duniverse.~dev] synchronised from git+file:///home/antonin/duniverse#master

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of duniverse failed at "/home/antonin/.opam/opam-init/hooks/sandbox.sh build dune build -p duniverse -j 11
        @install".

#=== ERROR while compiling duniverse.~dev =====================================#
# context     2.0.6 | linux/x86_64 | ocaml-system.4.09.0 | pinned(git+file:///home/antonin/duniverse#master#44b74dc6)
# path        ~/.opam/default/.opam-switch/build/duniverse.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p duniverse -j 11 @install
# exit-code   1
# env-file    ~/.opam/log/duniverse-151732-60459a.env
# output-file ~/.opam/log/duniverse-151732-60459a.out
### output ###
#     discover duniverse/base.v0.13.0/src/mpopcnt.sexp (exit 2)
# (cd _build/default/duniverse/base.v0.13.0/src && discover/discover.exe -o mpopcnt.sexp)
# Fatal error: exception Configurator__V1.Fatal_error("Configurator scripts must be run with Dune. To manually run a script, use $ dune exec.")



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build duniverse ~dev
└─ 
╶─ No changes have been performed
```

As you predicted, adding `(data_only_dirs duniverse)` produced a working executable.

**Comment by MisterDA** [comment]
It might be interesting to do a batch update of all the dependencies in the `duniverse/` directory, now that OCaml 4.10 is out. For instance, ppxlib.0.10.0 does not build, but is fixed in its last (0.12.0) version.
```
File "duniverse/ppxlib.0.10.0/ast/pprintast.ml", line 1301, characters 17-25:
1301 |             else Misc.may (pp f "(%s:%a)" s.txt (module_type ctxt)) mt;
                        ^^^^^^^^
Error: Unbound value Misc.may
```

**Comment by NathanReb** [comment]
Yeah you're right that it needs to be fixed! I'll try to take a look ASAP!

If you don't mind, I'd like to close this issue and open a separate one about updating and fixing the duniverse specifically.

**Comment by MisterDA** [comment]
> Also note that the documentation for this option isn't up to date

It would be nice to update the documentation with all the available options.
